title: Samen Games
description: Samen Games official website. Samen is more fun.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://samen-games.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
